name: 2w12-backend
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - numpy=1.24.3
  - scipy=1.11.4
  - matplotlib=3.8.2
  - ffmpeg=4.4.2
  - portaudio=19.6.0
  - pip=23.3.1
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - python-multipart==0.0.6
    - librosa==0.10.1
    - requests==2.31.0
    - redis==5.0.1
    - yt-dlp==2023.11.16
    - essentia-tensorflow==2.1b6.dev1110
    - aubio==0.4.9
    - Pillow==10.1.0
    - pydantic==2.5.0
    - python-jose==3.3.0
    - passlib==1.7.4
    - aiofiles==23.2.1
    - python-dotenv==1.0.0
    - psutil==5.9.5